from selenium.webdriver.common.by import By

class Locators:
    from_field = (By.ID, 'from')
    to_field = (By.ID, 'to')
    request_taxi_button = (By.CSS_SELECTOR, ".button.round")
    comfort_rate_icon = (By.XPATH, "//div[@class='tcard-title' and text()='Comfort']")
    phone_field = (By.CLASS_NAME, 'np-text')
    phone_input = (By.ID, 'phone')
    phone_next_button = (By.XPATH, "//button[text()='Siguiente']")
    sms_input_code = (By.XPATH, "//div[@class='np-input']/div/input[@id='code']")
    sms_confirm_button = (By.XPATH, "//button[text()='Confirmar']")
    payment_method_field = (By.CLASS_NAME, "pp-text")
    add_card = (By.CLASS_NAME, "pp-plus-container")
    card_number = (By.ID, 'number')
    card_code = (By.XPATH, "//div[@class='card-code-input']/input[@id='code']")
    card_second_row = (By.CLASS_NAME, "card-second-row")
    add_button = (By.XPATH, "//button[@class='button full' and text()='Agregar']")
    payment_method_close_button = (By.XPATH, "//div[@class='payment-picker open']/div/div[@class='section active']/button[@class='close-button section-close']")
    message_driver_field = (By.ID, "comment")
    slider_round = (By.XPATH, "//div[@class='r-sw-label'][contains(text(), 'Manta y pañuelos')]/following-sibling::div[@class='r-sw']/div[@class='switch']/span[@class='slider round']")
    check_slider_still_on = (By.XPATH, "//div[@class='r-sw-label' and text()='Manta y pañuelos']")
    ice_cream_counter_plus = (By.XPATH, "//div[@class='r sub r-type-counter'][.//div[@class='r-counter-label' and contains(text(), 'Helado')]]//div[@class='counter-plus']")
    ice_cream_counter_value = (By.XPATH, "//div[@class='r sub r-type-counter'][.//div[@class='r-counter-label' and contains(text(), 'Helado')]]//div[@class='counter']/div[@class='counter-value']")
    order_taxi_button_text = (By.XPATH, "//span[text()='Pedir un taxi']")
    order_taxi_button = (By.CLASS_NAME, "smart-button")
    order_body_window = (By.CLASS_NAME, "order-header-title")
    order_body_window_final = (By.CLASS_NAME, "order-number")
